# Generated by Django 6.0.3 on 2026-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('CTF', 'CTF Writeup'), ('Lab', 'Lab Exercise'), ('General', 'General')], default='CTF', max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('summary', models.CharField(help_text='Short description shown on blog cards', max_length=300)),
                ('content', models.TextField(help_text='Write your post in Markdown')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
